### ISSUE TITLE
Confused with v1.7b

### ISSUE THREAD

**Issue by ANTI443** [Droid-MAX/SNANDer#1]
Could you type a walk through from start to finish?

I'm confused on what to do.

Do we need MCMCCRU SNANDer first? 
Or do we just install your SNANDer only? 

When v1.7b is downloaded what Directory do we go in to run ./SNANDer -i?

Do we have to place v1.7b in any specific area?

I'm using Ubuntu Linux 

Thank you
 sorry not the smartest.

**Comment by Droid-MAX** [comment]
Sorry to reply you so late, The source code of the SNANDer v1.7b version corresponds to the dev-kioxia branch. The patch file of MCMCCRU is applied to the v1.7 version, and the flash memory chip for KIOXIA TC58CVG2S0HRAIJ is added.
In addition, the compilation method for the Linux system has been explained in the README file. You can refer to the execution command line to compile. And it also supports static compilation and compilation as a deb installation package. For details, please see the Makefile file in the src directory.

**Comment by Droid-MAX** [comment]
The zip package in the file I released is generally a package for the Windows platform
