### ISSUE TITLE
support for winbond w25q64jvsiq

### ISSUE THREAD

**Issue by xiv3r** [Droid-MAX/SNANDer#10]

**Comment by Droid-MAX** [comment]
参考W25Q64BV，已支持的器件请不要重复申请添加，谢谢！

**Comment by xiv3r** [comment]
winbond W25Q64JV is different from W25Q64JV-xM/BV/CV/FV

**Comment by Droid-MAX** [comment]
You can check that datasheet, the same device id and features.

**Comment by Droid-MAX** [comment]
有可能是接线问题，也有可能是你的编程器有问题，但绝不可能是不支持这个芯片

**Comment by Droid-MAX** [comment]
Is W25Q64JVIM?

**Comment by Droid-MAX** [comment]
https://github.com/Droid-MAX/SNANDer/commit/d5a8506c4e5ace12313af68c6abf4f173299f81e
