### ISSUE TITLE
能否打包一个Apple silicon 版本的？

### ISSUE THREAD

**Issue by andyhuai** [Droid-MAX/SNANDer#11]
本地尝试编译没有成功，能否编译一个 mac 版本的？

**Comment by Droid-MAX** [comment]
@andyhuai build-for-darwin.sh这个脚本其实我还没测试过，没有mac机器以及相关开发需求，所以还需要有人协助测试编译脚本

**Comment by Droid-MAX** [comment]
@andyhuai build-for-darwin.sh脚本修改好了，可以在你机器本地上尝试编译，注意先在线安装好libusb-1.0相关软件包
