### ISSUE TITLE
Please add support for W25Q128FV

### ISSUE THREAD

**Issue by DRCRecoveryData** [Droid-MAX/SNANDer#13]
![2023-10-04_193935](https://github.com/Droid-MAX/SNANDer/assets/85211068/31ba13fa-4d8e-4ee0-bbbb-b1175b463950)
My chip is W25Q128FV
![image](https://github.com/Droid-MAX/SNANDer/assets/85211068/ddbcc717-bbed-4290-8af1-929e88790e2a)
but SNANDer not have it and show wrong W25Q128BV

**Comment by Droid-MAX** [comment]
Same jedec id and features, so I will keep it.
