### ISSUE TITLE
plz add support for gigadevice GD5F2GM7REYIG

### ISSUE THREAD

**Issue by alexxiangyu** [Droid-MAX/SNANDer#20]
gigadevice GD5F2GM7REYIG

**Comment by Droid-MAX** [comment]
waitting for test

**Comment by alexxiangyu** [comment]
可以是识别到闪存，也能擦除，读取，读取内容是否能用还需要测试。

**Comment by alexxiangyu** [comment]
读取两遍，两次的文件对比都有小部分差异

**Comment by alexxiangyu** [comment]
备份两次出来的文件进行对比，都有小差异。&nbsp;


***@***.***
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年11月2日(星期六) 下午2:28
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Droid-MAX/SNANDer] plz add support for gigadevice GD5F2GM7REYIG (Issue #20)















等待测试

-
直接回复这封邮件，在GitHub上查看，或取消订阅.
***@***.*** &gt;

**Comment by Droid-MAX** [comment]
使用-d参数禁止使用内部ecc校验

**Comment by alexxiangyu** [comment]
可以使用，虽然刷回效验报错BAD 但是能 启动

**Comment by Droid-MAX** [comment]
ok, well done.
