### ISSUE TITLE
plz add support for micron MT29F2G01ABBGDWB

### ISSUE THREAD

**Issue by alexxiangyu** [Droid-MAX/SNANDer#21]

**Comment by Droid-MAX** [comment]
have you checked support list?

**Comment by alexxiangyu** [comment]
查过了，347识别不了闪存



---Original---
From: ***@***.***&gt;
Date: Fri, Nov 8, 2024 10:41 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Droid-MAX/SNANDer] plz add support for micron MT29F2G01ABBGDWB(Issue #21)




 
have you checked support list?

**Comment by Droid-MAX** [comment]
代码没问题

**Comment by alexxiangyu** [comment]
安装了的 刷过其他几个芯片了



---Original---
From: ***@***.***&gt;
Date: Fri, Nov 8, 2024 11:25 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Droid-MAX/SNANDer] plz add support for micron MT29F2G01ABBGDWB(Issue #21)




 
ch347需要装沁恒官方的驱动，下载release里面那个压缩包文件，里面有驱动安装程序

**Comment by Droid-MAX** [comment]
换个同型号的芯片试试？

**Comment by alexxiangyu** [comment]
用341A Nero p编程器软件可以识别到芯片



---Original---
From: ***@***.***&gt;
Date: Fri, Nov 8, 2024 11:28 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Droid-MAX/SNANDer] plz add support for micron MT29F2G01ABBGDWB(Issue #21)




 
换个同型号的芯片试试？

**Comment by Droid-MAX** [comment]
截图

**Comment by alexxiangyu** [comment]
晚上回去截图发你看看



---Original---
From: ***@***.***&gt;
Date: Fri, Nov 8, 2024 11:31 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Droid-MAX/SNANDer] plz add support for micron MT29F2G01ABBGDWB(Issue #21)




 
截图

**Comment by Droid-MAX** [comment]
能不能识别出来芯片？还是说只是读写擦除有问题？

**Comment by Droid-MAX** [comment]
上截图

**Comment by Droid-MAX** [comment]
工作电压设置正确？3.3v哦

**Comment by alexxiangyu** [comment]
这个芯片是1.8v吧



---Original---
From: ***@***.***&gt;
Date: Fri, Nov 8, 2024 16:53 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Droid-MAX/SNANDer] plz add support for micron MT29F2G01ABBGDWB(Issue #21)




 
工作电压设置正确？3.3v哦

**Comment by alexxiangyu** [comment]
***@***.***
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Droid-MAX/SNANDer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月8日(星期五) 下午4:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Droid-MAX/SNANDer] plz add support for micron MT29F2G01ABBGDWB (Issue #21)





 
工作电压设置正确？3.3v哦

**Comment by Droid-MAX** [comment]
你这发的啥啊？

**Comment by alexxiangyu** [comment]
341 识别芯片的截图，前面是发的347识别芯片的截图


***@***.***
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Droid-MAX/SNANDer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月8日(星期五) 下午5:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Droid-MAX/SNANDer] plz add support for micron MT29F2G01ABBGDWB (Issue #21)





 
你这发的啥啊？

**Comment by Droid-MAX** [comment]
看不到

**Comment by alexxiangyu** [comment]
![QQ图片20241108181044](https://github.com/user-attachments/assets/cba2b8c8-67f1-47fc-81ec-a11fb60597be)
![QQ截图20241108180727](https://github.com/user-attachments/assets/cff0c40f-745a-438a-b71e-3352c21c7891)
![QQ图片20241108173437](https://github.com/user-attachments/assets/ea36a2e4-abe9-45db-89d8-4e09a6ac9453)
原来邮箱回复的图片不显示。

**Comment by Droid-MAX** [comment]
无语了，这款芯片的数据手册对应的jedec id是2c24，但你这实际读取到的是2c25

**Comment by Droid-MAX** [comment]
你手上的这个型号的芯片读取出来的id都是2c25么？

**Comment by alexxiangyu** [comment]
是的 用neoprogrammer读取出来是2C25

**Comment by Droid-MAX** [comment]
得需要更多的样本数据比对

**Comment by Droid-MAX** [comment]
把芯片丝印给拍张照片

**Comment by alexxiangyu** [comment]
![QQ图片20241108185715](https://github.com/user-attachments/assets/d93bc83a-e90e-415c-b2ae-c087efbe7468)

**Comment by Droid-MAX** [comment]
你有MT29F2G01ABB的数据手册么？我没找到

**Comment by Droid-MAX** [comment]
猜测3.3v版本和1.8v版本之间的jedec id不同

**Comment by Droid-MAX** [comment]
NW874 - MT29F2G01ABA (3.3V, JEDEC-ID: 2C24)
NW875 - MT29F2G01ABB (1.8V,  JEDEC-ID: 2C25)

**Comment by alexxiangyu** [comment]
是的 两个型号只是电压区别。至于ID应该也是有区别的

**Comment by Droid-MAX** [comment]
well done, ready to test.

**Comment by alexxiangyu** [comment]
![QQ截图20241108202838](https://github.com/user-attachments/assets/d0d69619-61e7-4ec5-9361-eae4d7903669)
可以了

**Comment by Droid-MAX** [comment]
读写擦除都测试一下？

**Comment by alexxiangyu** [comment]
读没试，擦除写入效验都试过了

**Comment by Droid-MAX** [comment]
ok
