### ISSUE TITLE
CH347无法识别 MXIC MX35LF2GE4AB

### ISSUE THREAD

**Issue by qyyd5g** [Droid-MAX/SNANDer#22]
spi device id: 0 61 9 ff ff (6109ffff)
SPI NOR Flash Not Detected!
spi_nand_probe: mfr_id = 0xe1, dev_id = 0x9, dev_id_2 = 0x9
SPI NAND Flash Not Detected!

用ch347无法识别，不是CH347T

**Comment by Droid-MAX** [comment]
芯片丝印照片？

**Comment by Droid-MAX** [comment]
识别的id都不对，自己检查一下器件是否一致，工作电压是否符合要求

**Comment by qyyd5g** [comment]
> 识别的id都不对，自己检查一下器件是否一致，工作电压是否符合要求

换了ch341a能够识别，就是ch347（姚杰电子那个）就是不行

**Comment by Droid-MAX** [comment]
我还没有测试过在linux上使用ch347版本的snander能否正常使用
